fix OverflowError: Python int too large to convert to C long
Problem:-
OverflowError: Python int too large to
convert to C long, in 32bit linux builds

- start_new_thread method should return
  a c long (untill 3.6) and unsigned long
  (3.7 onwards).
- In interrupt_func we use saving return of
  start_new_thread as long.

Solution:-
- Using unsigned long caused sign
  conversion error.
- So long long is used to save return

Squashed commit of the following:

commit 4aa6f604b5af0853bc4aacdc7936378ebd17579f
Author: Ashutosh Varma <ashutoshvarma11@live.com>
Date:   Tue Dec 22 19:13:58 2020 +0530

    re-enable windows and mac builds in azp

commit 422b0fb7d96a38b9eea91dd63f56cc7a44867985
Author: Ashutosh Varma <ashutoshvarma11@live.com>
Date:   Tue Dec 22 18:12:29 2020 +0530

    change tid to long long in interrupt_func

commit c878ec33e247eb1931f638f87bd8342bb8d4bd2b
Author: Ashutosh Varma <ashutoshvarma11@live.com>
Date:   Tue Dec 22 18:00:39 2020 +0530

    try another fix

commit 17bccf4bf49abedb27b10144bc48f6187e13e05e
Author: Ashutosh Varma <ashutoshvarma11@live.com>
Date:   Tue Dec 22 17:47:40 2020 +0530

    revert debug changes

commit 05c301001e4c2844eed1b8626337936fa197ca33
Author: Ashutosh Varma <ashutoshvarma11@live.com>
Date:   Tue Dec 22 16:46:08 2020 +0530

    debug changes

commit 5d8074b63c7134cc0bab5110d54234e78f6c9a2b
Author: Ashutosh Varma <ashutoshvarma11@live.com>
Date:   Tue Dec 22 16:33:45 2020 +0530

    disable wheel building for cp37-manylinux_i686